# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://ssomal62.github.io/"
defaultContentLanguage = "ko"

enableRobotsTXT = false
summaryLength = 0
languageCode = "ko"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["devl", "posts", "about"]


[params.list]
groupByYear = true

[pagination]
pagerSize = 10

ignoreLogs = ['warning-partial-superfluous-prefix']

